name: Publish Markdown Files

env:
  SOURCE_DIRECTORY: published # Replace with the path to the directory you want to copy
  TARGET_REPO: ${{ secrets.TARGET_REPO }}
  TARGET_DIRECTORY: src/content/post # Replace with the path to the directory you want to replace
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source_repo
          fetch-depth: 0

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ env.PERSONAL_ACCESS_TOKEN }}
          path: target_repo

      - name: Remove existing contents in target directory
        run: |
          rm -rf target_repo/${{ TARGET_DIRECTORY }}/*

      - name: Copy directory contents from source to target
        run: |
          cp -r source_repo/${{ SOURCE_DIRECTORY }}/. target_repo/${{ TARGET_DIRECTORY }}/

      - name: Commit and push changes
        run: |
          cd target_repo
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Replace directory contents"
          git push
