name: Publish Markdown Files

on:
  push:
    branches:
      - main # Replace with the branch you want to monitor

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy directory
        env:
          TARGET_REPO: ${{ secrets.TARGET_REPO }}
          TARGET_DIRECTORY: src/content/post # Replace with the path to the directory you want to replace
          SOURCE_DIRECTORY: published # Replace with the path to the directory you want to copy
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git clone https://${PERSONAL_ACCESS_TOKEN}@github.com/${TARGET_REPO}.git srleom/blog
          rm -rf srleom/blog/${TARGET_DIRECTORY}
          cp -r ${SOURCE_DIRECTORY} srleom/blog/${TARGET_DIRECTORY}
          cd srleom/blog
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update ${TARGET_DIRECTORY} from source repository"
          git push
